### ISSUE TITLE
config SSL dnms

### ISSUE THREAD

**Issue by hardiagunadi** [daimus/dnms#1]
Mas Daimus sebelumnya saya mengucapkan terima kasih, aplikasnya sangat bermanfaat. 
saya mau tanya untuk untuk menggunakan fitur ssl di vps adakah config di dnms yang perlu dirubah. saat ini saya mengintall dnms di vps pribadi dan sudah mengaktifkan SSL untuk mencoba fitur radar scheduler, namun saya akses dnms menggunakan https belum bisa diakses. mohon bantuanya..

**Comment by daimus** [comment]
Sebelumnya terima kasih Mas Hardi.
Tidak ada konfigurasi apapun di dnms jika ingin menggunakan protokol HTTPS.
Mengenai fitur radar scheduler, saya kira masalahnya bukan protocol HTTP/S, melainkan radar scheduler diblock oleh middleware. Seharusnya 6d22ef1 bisa menyelesaikan masalah Mas Hardi.
Semoga membantu 🙇

**Comment by hardiagunadi** [comment]
iya mas, sudah saya coba lagi bisa, termasuk setingan server saya juga bermsalah. saya beralih menggunakan nginx ssl berjalan baik  pakai metode  http proxy
config nginx server yang saya gunakan 
`	server {
location / {
	
		proxy_pass http://localhost:3000;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection 'upgrade';
		proxy_set_header Host $host;
		proxy_cache_bypass $http_upgrade;
}
`
dengan ssl bisa berjalan baik
![image](https://user-images.githubusercontent.com/16506204/121537032-c311e100-ca2d-11eb-8b7f-2ac2d63b07fa.png)
cron saya menggunakan curl
![image](https://user-images.githubusercontent.com/16506204/121537494-2a2f9580-ca2e-11eb-9b13-e5cb74222c5d.png)
di .env  token dan  chatid sudah saya set, saya coba tunggu respon bot belum ada tanda2 respon apa konfigurasi saya ada yang belum sesuai mas?

**Comment by hardiagunadi** [comment]
respon link cron saat saya coba buka manual di browser.
![image](https://user-images.githubusercontent.com/16506204/121538384-f0ab5a00-ca2e-11eb-9fef-c363b546943a.png)

**Comment by daimus** [comment]
Sebelumnya pastikan bot telegram Mas Hardi bisa menerima pesan. Cek juga status pengiriman pesan di log.
Sebagai tambahan informasi dnms tidak akan mengirim pesan jika send report dimatikan dan semua device dalam keadaan online.

**Comment by hardiagunadi** [comment]
baik mas saat ini sedang saya coba cek ulang. untuk Create scheduler/cron job to execute this link https://your_domain_or_ip/scheduler/radar/run 
eksekusinya di cron/schedule server linux atau di mikrotiknya mas

**Comment by daimus** [comment]
Sebaiknya di server/host tempat dnms diinstall mas

**Comment by hardiagunadi** [comment]
baik mas, terima kasih responya. sudah teratasi
