### ISSUE TITLE
Request Fitur Search pada penambahan perangkat dengan discover

### ISSUE THREAD

**Issue by hardiagunadi** [daimus/dnms#2]
Mas Daimus bilamana memungkinkan saya request fitur search saat menambahkan perangkat dengan discover, sehingga bisa mencari perangkat lebih cepat. baik di Neighbor, ARP, DHCP Lease dan Hostpot host untuk mecari perangkat dengan jumlah banyak harus mengurutkan satu per satu. fitur seacrh pada browser kadang tidak bisa untuk mencarinya.

**Comment by daimus** [comment]
Halo Mas Hardi, fitur tersebut sudah saya tambah pada commit ini ya d073e7f
Terima kasih atas sarannya :)
Salam
